### ISSUE TITLE
mongodb.open is not a function

### ISSUE THREAD

**Issue by wanjuawan1234** [RyanRong/microblog#1]
大牛，系统启动报错：mongodb.open is not a function，

**Comment by RyanRong** [comment]
@wanjuawan1234 我严重怀疑是你代码抄错了 ~

**Comment by wanjuawan1234** [comment]
…………Post.get = function get(username, callback) {
    mongodb.open(function (err, db) {
        if (err) {
            return callback(err);

        }
        //读取posts集合
        db.collection('posts', function (err, collection) {
            if (err) {
                mongodb.close();
                return callback(err);
            }
            //查找user属性为username的文档，如果username是null则匹配全部
            var query = {};
            if (username) {
                query.user = username;
            }
            collection.find(query).sort({time: -1}).toArray(function (err, docs) {
                mongodb.close();
                if (err) {
                    callback(err, null);
                }
                //封装posts为Post对象
                var posts = [];
                docs.forEach(function (doc, index) {
                    var post = new Post(doc.user, doc.post, doc.time);
                    posts.push(post);

                });
                callback(null, posts);


            });

        });

    });
};会不会是mongodb的版本问题

**Comment by wanjuawan1234** [comment]
我是克隆过来，然后在npm上安装的配置项

**Comment by wanjuawan1234** [comment]
TypeError: mongodb.open is not a function
    at Function.get (e:\workespace\microblog-master\models\post.js:42:13)
    at e:\workespace\microblog-master\routes\index.js:8:10
    at Layer.handle [as handle_request] (e:\workespace\microblog-master\node_modules\express\lib\router\layer.js:95:5)
    at next (e:\workespace\microblog-master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (e:\workespace\microblog-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (e:\workespace\microblog-master\node_modules\express\lib\router\layer.js:95:5)
    at e:\workespace\microblog-master\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (e:\workespace\microblog-master\node_modules\express\lib\router\index.js:335:12)
    at next (e:\workespace\microblog-master\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (e:\workespace\microblog-master\node_modules\express\lib\router\index.js:174:3)
访问localhost：3000能进入页面，但是报错，大牛可否赐教小弟，小弟甚是不解

**Comment by RyanRong** [comment]
@wanjuawan1234  npm install的时候 是根据我package.json的版本来安装的.应该跟clone的关系不大啊 !
mongodb是数据库,操作数据库的是接口,是不是你配置的数据库出现了一些问题.

**Comment by RyanRong** [comment]
@wanjuawan1234  mongodb.open is not a function  你看 mongodb这个对象导入 或者初始化了没有

**Comment by wanjuawan1234** [comment]
![mongo](https://user-images.githubusercontent.com/34568661/34038187-70b86a8a-e1c6-11e7-9e6c-f149593ac89c.png)
